// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20230710065548_first23")]
    partial class first23
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BE.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Addres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BE.Company_Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ComparyID")
                        .HasColumnType("int");

                    b.Property<int?>("TicketBEID")
                        .HasColumnType("int");

                    b.Property<int>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("TicketBEID");

                    b.ToTable("Company_Tickets");
                });

            modelBuilder.Entity("BE.TicketBE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Mabdae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maghsad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("TypeAir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numAIR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BE.Company_Ticket", b =>
                {
                    b.HasOne("BE.Company", "Company")
                        .WithMany("company_Tickets")
                        .HasForeignKey("CompanyID");

                    b.HasOne("BE.TicketBE", "TicketBE")
                        .WithMany("company_Tickets")
                        .HasForeignKey("TicketBEID");

                    b.Navigation("Company");

                    b.Navigation("TicketBE");
                });

            modelBuilder.Entity("BE.Company", b =>
                {
                    b.Navigation("company_Tickets");
                });

            modelBuilder.Entity("BE.TicketBE", b =>
                {
                    b.Navigation("company_Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
